site_name: BHFF Tutoring program
# site_url:

repo_url: https://github.com/neuralmaticv/bhff-tutoring
repo_name: neuralmaticv/bhff-tutoring

#
# Theme Settings
#

plugins:
  - search

theme:
  name: material
  logo: assets/images/bhff-favicon.png
  favicon: assets/images/bhff-favicon.png

  features:
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.tabs
    - navigation.sections
    - navigation.path
    # - navigation.tabs.sticky
    # - navigation.expand

    # Table of contents
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
    - toc.integrate

    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#setting-up-site-search    - search.suggest
    - search.suggest
    - search.highlight

    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: bhff
      toggle:
        icon: material/weather-sunny
        name: Prebaci na tamni mod

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Prebaci na svijetli mod

#
# Extra Settings
#
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/bhff
      name: BHFF GitHub Org

extra_css:
  - assets/css/extra.css

#
# Extensions
#
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - attr_list

  - admonition
  - footnotes

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
#
# Navigation
# https://www.mkdocs.org/user-guide/configuration/#nav
#

nav:
  - Početna: index.md
  - Dodavanje zadataka: instructions.md
  - Matematika:
      - Uvod: content/matematika/index.md
      - Prvi razred:
          - Uvod: content/matematika/1/index.md
      - Drugi razred:
          - Uvod: content/matematika/2/index.md
          - Geometrija: content/matematika/2/geometrija.md
      - Treći razred:
          - Uvod: content/matematika/3/index.md
      - Četvrti razred:
          - Uvod: content/matematika/4/index.md
      - Resursi i materijali: content/matematika/resources.md
  - Fizika:
      - Uvod: content/fizika/index.md
      - Prvi razred:
          - Uvod: content/fizika/1/index.md
      - Drugi razred:
          - Uvod: content/fizika/2/index.md
      - Treći razred:
          - Uvod: content/fizika/3/index.md
      - Četvrti razred:
          - Uvod: content/fizika/4/index.md
      - Resursi i materijali: content/fizika/resources.md
  - Hemija:
      - Uvod: content/hemija/index.md
      - Prvi razred:
          - Uvod: content/hemija/1/index.md
      - Drugi razred:
          - Uvod: content/hemija/2/index.md
      - Treći razred:
          - Uvod: content/hemija/3/index.md
      - Četvrti razred:
          - Uvod: content/hemija/4/index.md
      - Resursi i materijali: content/hemija/resources.md
  - Programiranje:
      - Uvod: content/programiranje/index.md
      - Prvi razred:
          - Uvod: content/programiranje/1/index.md
          - Python:
              - Uvod: content/programiranje/1/python/index.md
          - JavaScript:
              - Uvod: content/programiranje/1/javascript/index.md
          - C (C++):
              - Uvod: content/programiranje/1/cpp/index.md
      - Drugi razred:
          - Uvod: content/programiranje/2/index.md
          - Python:
              - Uvod: content/programiranje/2/python/index.md
          - JavaScript:
              - Uvod: content/programiranje/2/javascript/index.md
          - C (C++):
              - Uvod: content/programiranje/2/cpp/index.md
      - Treći razred:
          - Uvod: content/programiranje/3/index.md
          - Python:
              - Uvod: content/programiranje/3/python/index.md
          - JavaScript:
              - Uvod: content/programiranje/3/javascript/index.md
          - C (C++):
              - Uvod: content/programiranje/3/cpp/index.md
      - Četvrti razred:
          - Uvod: content/programiranje/4/index.md
          - Python:
              - Uvod: content/programiranje/4/python/index.md
          - JavaScript:
              - Uvod: content/programiranje/4/javascript/index.md
          - C (C++):
              - Uvod: content/programiranje/4/cpp/index.md
      - Resursi i materijali: content/programiranje/resources.md
